using UnityEngine;

class Movement
{
    private readonly Transform _target;
    private readonly Stats _stats;

    public Movement(Transform target, Stats stats)
    {
        _target = target;
        _stats = stats; 
    }

    public void Move(Vector3 direction)
    {
        _target.position += direction * (_stats.Speed * Time.deltaTime);
    }
}

class KeyBindings
{
    public Vector2 GetInput()
    {
        return new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));
    }
}

// monoBehaviourì— ì§ì ‘ ê¸°ëŠ¥ì´ ë“¤ì–´ê°€ë©´ ìœ„ì¹˜ ì„ ì •ë„ ì–´ë µê³  ê¹”ë”í•˜ì§€ ì•Šì•„ ë¶„ë¦¬í•œë‹¤.
public class PlayerController : MonoBehaviour
{
    private Movement _movement;
    // learn: í•„ë“œì—ì„œ ì§ì ‘ ê°’ì„ ë“±ë¡í•˜ëŠ” ê²ƒì€ ì¶”ìƒì  í˜•íƒœë¥¼ ë°›ëŠ” ìœ ì—°ì„±ì—ì„œ ë–¨ì–´ì§€ë‚˜, ì´ì²˜ëŸ¼ ëª…ë£Œí•œ ê´€ê³„ë¥¼ ê°€ì§ˆ ë•ŒëŠ” ìœ íš¨í•œ ë°©ì‹ì´ë‹¤.
    private readonly KeyBindings _keyBindings = new KeyBindings();
    private Stats _stats;
    
    [HideInInspector] public ResourceController ResourceController;

    void Start()
    {
        // ì˜ì¡´ ê´€ê³„ ìƒì„±(í”Œë ˆì´ì–´ ìŠ¤í¬ë¦½íŠ¸ë¥¼ í˜¸ì¶œí•  ë•Œ Stats ì»´í¬ë„ŒíŠ¸ê°€ í•„ìˆ˜ê°€ ë˜ì–´ë²„ë¦¼
        _stats = GetComponent<Stats>();
        ResourceController = new ResourceController(_stats);
        // stats ìì²´ë¥¼ ë„£ì–´ì•¼ ëŸ°íƒ€ì„ì—ì„œ ì¸ìŠ¤í™í„° ë‚´ ê°’ì„ ë³€ê²½í•´ë„ ì¸ì§€ ê°€ëŠ¥
        _movement = new Movement(transform, _stats);

    }
    void Update()
    {
        Vector2 input = _keyBindings.GetInput(); // ğŸ”¥ í‚¤ ë°”ì¸ë”ì—ì„œ ì…ë ¥ ê°€ì ¸ì˜¤ê¸°
        _movement.Move(input);
    }
}